version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  groceteria.catalogue.api:
    image: ${DOCKER_REGISTRY-}groceteriacatalogueapi
    build:
      context: .
      dockerfile: services/catalogue/Groceteria.Catalogue.Api/Dockerfile

networks:
  groceteria:
    driver: bridge

volumes:
  elasticsearch-data: