version: '3.4'

services:
  cataloguedb:
    container_name: cataloguedb
    volumes:
       - cataloguedb_data:/data/db
    ports:
       - "27017:27017"
    networks:
      - groceteriaApiGateway

  cataloguedbViewer:
    container_name: cataloguedbViewer
    depends_on:
       - cataloguedb
    environment:
        - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
        - ME_CONFIG_MONGODB_SERVER=cataloguedb
    ports:
        - "8081:8081"

  basketdb:
    container_name: basketdb
    ports:
      - "6379:6379"
  basketdbViewer:
    container_name: basketdbViewer
    depends_on:
       - basketdb
    environment:
       - REDIS_HOST=basketdb:6379 
    ports:
       - 8082:8081  

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Orderdb@123
      - MSSQL_PID=Express 
    ports:
      - 1433:1433
    volumes:
      - salesorder_data:/var/opt/mssql
   
  identityProviderDb:
    container_name: identityProviderDb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
    ports:
      - 1435:1433
    volumes:
      - identity_data:/var/opt/mssql
    networks:
      - groceteriaIdentity

  rabbitmq:
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=Passw0rd

  discountdbViewer:
    container_name: discountdbViewer
    depends_on:
      - discountdb
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@groceteria.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234  
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  notificationProcessordb:
    container_name: notificationProcessordb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=notification@123
      - MSSQL_PID=Express
    ports:
      - 1434:1433
    volumes:
      - notificationProcessor_data:/var/opt/mssql

  elasticsearch:
    container_name: 'elasticsearch'
    ports:
    - 9200:9200
    volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node

  kibana:
    container_name: kibana
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200

  portainer:
    container_name: portainer
    ports:
    - 7000:8000
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data 

  groceteria.catalogue.api:
    container_name: groceteria.catalogue.api
    depends_on:
      - cataloguedb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LoggerConfigOption:OverrideSource=Microsoft
      - LoggerConfigOption:OutputTemplate={NewLine} [{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {Properties} {NewLine} {Message} {Exception}
      - "Elasticsearch:Uri=http://elasticsearch:9200"
      - "MongodbSettings:ConnectionString=mongodb://cataloguedb:27017"
      - "MongodbSettings:Database=catalogueDb"
    ports:
      - "8000:80"
    networks:
      - groceteriaApiGateway

  groceteria.basket.api:
    container_name: groceteria.basket.api
    depends_on:
      - basketdb
      - groceteria.catalogue.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LoggerConfigOption:OverrideSource=Microsoft
      - LoggerConfigOption:OutputTemplate={NewLine} [{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {Properties} {NewLine} {Message} {Exception}
      - "Elasticsearch:Uri=http://elasticsearch:9200"
      - "CatalogueApiSettings:baseAddress=http://groceteria.apigateway/Catalogue"
      - "CatalogueApiSettings:version=v2"
      - "RedisCache:InstanceName=Groceteria.Basket.Cache"
      - "RedisCache:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://groceteria.discount.grpc"
      - "RabbitMq:ConnectionString=amqp://user:Passw0rd@rabbitmq:5672"
    ports:
      - "8001:80"


  groceteria.discount.grpc:
    container_name: groceteria.discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LoggerConfigOption:OverrideSource=Microsoft
      - LoggerConfigOption:OutputTemplate={NewLine} [{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {Properties} {NewLine} {Message} {Exception}
      - "Elasticsearch:Uri=http://elasticsearch:9200" 
      - "DiscountDb:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb 
    ports:
      - "8002:80"

  groceteria.notificationmessgae.processor:
    container_name: groceteria.notification.processor
    depends_on:
      - notificationProcessordb 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LoggerConfigOption:OverrideSource=Microsoft
      - LoggerConfigOption:OutputTemplate={NewLine} [{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {Properties} {NewLine} {Message} {Exception}
      - "Elasticsearch:Uri=http://elasticsearch:9200"
      -  "ProcessInterval=1"
      - "ConnectionStrings:NotificationProcessor=Server=notificationProcessordb;Database=NotificationDb;User Id=sa;Password=notification@123;"
      - "EmailSettingsOption:Server=sandbox.smtp.mailtrap.io"
      - "EmailSettingsOption:Port=25"
      - "EmailSettingsOption:CompanyAddress=care.groceteria.com"
      - "EmailSettingsOption:Username=1bc0ad2cff257e"
      - "EmailSettingsOption:Password=c0039b21a03f21"

  
  groceteria.saleseorder.api:
    container_name: groceteria.saleseorder.api
    depends_on:
      - orderdb
      - notificationProcessordb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LoggerConfigOption:OverrideSource=Microsoft
      - LoggerConfigOption:OutputTemplate={NewLine} [{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {Properties} {NewLine} {Message} {Exception}
      - "Elasticsearch:Uri=http://elasticsearch:9200"
      - "ConnectionStrings:NotificationProcessor=Server=notificationProcessordb;Database=NotificationDb;User Id=sa;Password=notification@123;"
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb,1433;Database=OrderDb;User Id=sa; Password=Orderdb@123;"
      - "RabbitMq:ConnectionString=amqp://user:Passw0rd@rabbitmq:5672"
    ports:
      - "8003:80"


  groceteria.apigateway:
    container_name: groceteria.apigateway
    depends_on:
      - groceteria.catalogue.api
      - groceteria.basket.api
      - groceteria.saleseorder.api 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT="8011"
      - LoggerConfigOption:OverrideSource=Microsoft
      - LoggerConfigOption:OutputTemplate={NewLine} [{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {Properties} {NewLine} {Message} {Exception}
      - "Elasticsearch:Uri=http://elasticsearch:9200"
    ports:
      - "8010:80"
      - "8011:443"
    networks:
      - groceteriaApiGateway
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/root/.aspnet/https


  groceteria.identityprovider:
    container_name: groceteria.identityprovider
    depends_on:
      - identityProviderDb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT="9001"
      - "Logging:IncludeScopes=false"
      - "Logging:LogOutputTemplate=[{Timestamp:dd-MM-yyyy HH:mm:ss, fff}] {Level} {Properties} [CorrelationId:{CorrelationId}] [Machine:{MachineName}] {CallerType}:{MemberName} {Message}{NewLine}{Exception}"
      - "Logging:Console=Enabled=true"
      - "Logging:Console=LogLevel=Debug"
      - "Logging:Elasticsearch=Enabled=true"
      - "Logging:Elasticsearch=LogLevel=Debug"
      - "AppConfigurations:ApplicationIdentifier=Groceteria.IdentityServer"
      - "AppConfigurations:ApplicationEnvironment=Development"
      - "Elasticsearch:Uri=http://elasticsearch:9200"
      - "ConnectionStrings:OAuthDb=Server=identityProviderDb;Database=GroceteriaIdentityDb;User Id=sa;Password=P@ssw0rd;"
      - "ConnectionStrings:UserDb=Server=identityProviderDb;Database=GroceteriaUserDb;User Id=sa;Password=P@ssw0rd;"
    ports:
      - "9002:80"
      - "9001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/root/.aspnet/https/
    networks:
      - groceteriaIdentity