version: '3.4'

services:
  cataloguedb:
    container_name: cataloguedb
    restart: always
    volumes:
       - cataloguedb_data:/data/db
    ports:
       - "27017:27017"

  cataloguedbViewer:
    container_name: cataloguedbViewer
    restart: always
    depends_on:
       - cataloguedb
    environment:
        - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
        - ME_CONFIG_MONGODB_SERVER=cataloguedb
    ports:
        - "8081:8081"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  basketdbViewer:
    container_name: basketdbViewer
    restart: always
    depends_on:
       - basketdb
    environment:
       - REDIS_HOST=basketdb:6379 
    ports:
       - 8082:8081  

  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  discountdbViewer:
    container_name: discountdbViewer
    restart: always
    depends_on:
      - discountdb
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@groceteria.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234  
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  elasticsearch:
    container_name: 'elasticsearch'
    restart: always
    ports:
    - 9200:9200
    volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node

  kibana:
    container_name: kibana
    restart: always
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200


  groceteria.catalogue.api:
    container_name: groceteria.catalogue.api
    restart: always
    depends_on:
      - cataloguedb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LoggerConfigOption:OverrideSource=Microsoft
      - LoggerConfigOption:OutputTemplate=[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {NewLine} {Properties} {NewLine} {NewLine} {Message} {Exception}
      - "Elasticsearch:Uri=http://elasticsearch:9200"
      - "MongodbSettings:ConnectionString=mongodb://cataloguedb:27017"
      - "MongodbSettings:Database=catalogueDb"
    ports:
      - "8000:80"

  groceteria.basket.api:
    container_name: groceteria.basket.api
    restart: always
    depends_on:
      - basketdb
      - groceteria.catalogue.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LoggerConfigOption:OverrideSource=Microsoft
      - LoggerConfigOption:OutputTemplate=[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {NewLine} {Properties} {NewLine} {NewLine} {Message} {Exception}
      - "Elasticsearch:Uri=http://elasticsearch:9200"
      - "CatalogueApiSettings:baseAddress=http://groceteria.catalogue.api"
      - "CatalogueApiSettings:version=v2"
      - "RedisCache:InstanceName=Groceteria.Basket.Cache"
      - "RedisCache:ConnectionString=basketdb:6379"
    ports:
      - "8001:80"

