version: '3.4'

services:
  cataloguedb:
    image: mongo
  cataloguedbViewer:
    image: mongo-express
  basketdb:
    image: redis:alpine
  discountdb:
    image: postgres
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
  notificationProcessordb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  identityProviderDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  discountdbViewer:
    image: dpage/pgadmin4
  basketdbViewer:
    image: rediscommander/redis-commander:latest
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
  portainer:
    image: portainer/portainer-ce

  groceteria.catalogue.api:
    image: ${DOCKER_REGISTRY-}groceteriacatalogueapi
    build:
      context: .
      dockerfile: services/catalogue/Groceteria.Catalogue.Api/Dockerfile

  groceteria.basket.api:
    image: ${DOCKER_REGISTRY-}groceteriabasketapi
    build:
      context: .
      dockerfile: services/basket/Groceteria.Basket.Api/Dockerfile

  groceteria.discount.grpc:
    image: ${DOCKER_REGISTRY-}groceteriadiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Groceteria.Discount.Grpc/Dockerfile

  groceteria.notificationmessgae.processor:
    image: ${DOCKER_REGISTRY-}groceterianotificationmessgaeprocessor
    build:
      context: .
      dockerfile: Services/Notification/Groceteria.NotificationMessgae.Processor/Dockerfile

  groceteria.saleseorder.api:
    image: ${DOCKER_REGISTRY-}groceteriasaleseorderapi
    build:
      context: .
      dockerfile: Services/SalesOrder/Groceteria.SaleseOrder.Api/Dockerfile

  groceteria.apigateway:
    image: ${DOCKER_REGISTRY-}groceteriaapigateway
    build:
      context: .
      dockerfile: Services/ApiGateways/Groceteria.ApiGateway/Dockerfile

  groceteria.identityprovider:
    image: ${DOCKER_REGISTRY-}groceteriaidentityprovider
    build:
      context: .
      dockerfile: Services/IdentityServer/Groceteria.IdentityProvider/Dockerfile

volumes:
  elasticsearch-data:
  cataloguedb_data:
  postgres_data:
  pgadmin_data:
  notificationProcessor_data:
  salesorder_data:
  portainer_data:
  identity_data:

networks:
  groceteriaIdentity:
    driver: bridge
  groceteriaApiGateway:
    driver: bridge