version: '3.4'

services:
  cataloguedb:
    image: mongo
  cataloguedbViewer:
    image: mongo-express
  basketdb:
    image: redis:alpine
  discountdb:
    image: postgres
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  discountdbViewer:
    image: dpage/pgadmin4
  basketdbViewer:
    image: rediscommander/redis-commander:latest
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  groceteria.catalogue.api:
    image: ${DOCKER_REGISTRY-}groceteriacatalogueapi
    build:
      context: .
      dockerfile: services/catalogue/Groceteria.Catalogue.Api/Dockerfile

  groceteria.basket.api:
    image: ${DOCKER_REGISTRY-}groceteriabasketapi
    build:
      context: .
      dockerfile: services/basket/Groceteria.Basket.Api/Dockerfile

  groceteria.discount.grpc:
    image: ${DOCKER_REGISTRY-}groceteriadiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Groceteria.Discount.Grpc/Dockerfile

volumes:
  elasticsearch-data:
  cataloguedb_data:
  postgres_data:
  pgadmin_data:

